Family/Controllers/FamilyMemberTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Family.Models;

namespace Family.Controllers
{
    public class FamilyMemberTypeController : Controller
    {
        // GET: FamilyMemberType
        public ActionResult Index()
        {
            DatabaseContext DatabaseContext = new DatabaseContext();
            List<FamilyMemberType> familyMemberTypes = DatabaseContext.FamilyMemberTypes.ToList();
            return View(familyMemberTypes);
        }

       /* public ActionResult FamilyMemberByTypeTotal()
        {
            DatabaseContext DatabaseContext = new DatabaseContext();
           var familyMember= DatabaseContext.FamilyMember.Include("FamilyMember")
                .GroupBy(x=>)
        }*/
    }
}

Family/Controllers/GroceryTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopGroceryBusinessLayer.Models;

namespace Family.Controllers
{
    public class GroceryTypeController : Controller
    {
        // GET: GroceryType
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ItemType()
        {
            GroceryTypeRepository groceryRepository = new GroceryTypeRepository();
            List<GroceryType> groceryTypes = groceryRepository.GroceryTypes.ToList();
            return View(groceryTypes);
        }

        [HttpGet]
        [ActionName("AddItemType")]
        public ActionResult AddItemTypeGet()
        {

            return View();
        }

        [HttpPost]
        [ActionName("AddItemType")]
        public ActionResult AddItemTypePost(GroceryType groceryType)
        {
            if (ModelState.IsValid)
            {
                GroceryTypeRepository groceryTypeRepository = new GroceryTypeRepository();
                groceryTypeRepository.Add(groceryType);
                return RedirectToAction("ItemType");
            }
            return View();
        }

        [HttpGet]
        [ActionName("EditItemType")]
        public ActionResult EditItemTypeGet(int id)
        {
            GroceryTypeRepository groceryTypeRepository = new GroceryTypeRepository();
            GroceryType groceryType= groceryTypeRepository.GroceryTypes.Single(gt => gt.GroceryItemTypeId == id);
            return View(groceryType);
        }

        [HttpPost]
        [ActionName("EditItemType")]
        public ActionResult EditItemTypePost(GroceryType groceryType)
        {
            if (ModelState.IsValid)
            {
                GroceryTypeRepository groceryTypeRepository = new GroceryTypeRepository();
                groceryTypeRepository.Edit(groceryType);
                return RedirectToAction("ItemType");
            }
            return View(groceryType);
        }
    }
}

Family/Controllers/ShopGroceryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopGroceryBusinessLayer.Models;
using Family.Models;

namespace Family.Controllers
{
    public class ShopGroceryController : Controller
    {
        // GET: Grocery

        public ActionResult Index1()
        {
            GroceryRepository groceryRepository = new GroceryRepository();

            List<Grocery> groceries = groceryRepository.Groceries.ToList();

            var groceryList = groceryRepository.GroceryTypes.ToList();

            var query = from gt in groceryList
                        join g in groceries on gt.GroceryItemTypeId equals g.GroceryItemTypeId
                        where g.GroceryItemTypeId == gt.GroceryItemTypeId
                        select new
                        {
                            gt.GroceryItemTypeName
                        };

            //ViewBag.GroceryItemTypeName = query.ToList(); 

            //var result = query.ToList();
            string GroceryItemTypeName = null;
            foreach (var result in query)
            {
                GroceryItemTypeName = result.GroceryItemTypeName;

                ViewBag.GroceryItemTypeName = GroceryItemTypeName;

            }
            GroceryViewModel groceryViewModel = new GroceryViewModel();

            List<GroceryViewModel> groceryViewModelList = groceries.Select(x => new GroceryViewModel
            {
                GroceryItemName = x.GroceryItemName,
                NoOfGroceryItem = x.NoOfGroceryItem,
                GroceryItemId = x.GroceryItemId,
                GroceryItemTypeId = x.GroceryItemTypeId,
                //GroceryItemTypeName=x.GroceryType.GroceryItemTypeName
                //GroceryItemTypeName = GroceryItemTypeName
                //GroceryItemTypeName = groceryList.Where(y => y.GroceryItemTypeId == x.GroceryItemTypeId)
                //.Select(y => y.GroceryItemTypeName).ToString()

            }).ToList();

            return View(groceryViewModelList);
           
            }

        public ActionResult Index()
        {
            GroceryRepository groceryRepository = new GroceryRepository();

            var groceries = (from g in groceryRepository.Groceries
                             join gt in groceryRepository.GroceryTypes
                             on g.GroceryItemTypeId equals gt.GroceryItemTypeId
                             select new GroceryViewModel
                             {
                                 GroceryItemId = g.GroceryItemId,
                                 GroceryItemName = g.GroceryItemName,
                                 NoOfGroceryItem=g.NoOfGroceryItem,
                                 GroceryItemTypeName = gt.GroceryItemTypeName
                             }).ToList();

            return View(groceries);
        }

        /* public ActionResult Index()
         {
             GroceryRepository groceryRepository = new GroceryRepository();

             List<Grocery> groceries = groceryRepository.Groceries.ToList();

             var groceryList = groceryRepository.GroceryTypes.ToList();
             var query = from gt in groceryList
                         join g in groceries on gt.GroceryItemTypeId equals g.GroceryItemTypeId
                         where g.GroceryItemTypeId == gt.GroceryItemTypeId
                         select new
                         {
                             gt.GroceryItemTypeName
                         };
             // var result = query.FirstOrDefault();
            // string GroceryItemTypeName = null;


             ViewBag.GroceryItemTypeName = query.ToList();
             return View(groceries);
         }*/

        /* public List<Grocery> Index()
         {
             GroceryRepository groceryRepository = new GroceryRepository();
             var groceries = groceryRepository.Groceries
                        .Select(b => new Grocery()
                        {
                            GroceryItemId = b.GroceryItemId,
                            GroceryItemName = b.GroceryItemName,
                            NoOfGroceryItem = b.NoOfGroceryItem,
                            GroceryTypes = b.GroceryTypes
                        });
             return groceries.ToList<Grocery>();
         }*/


        [HttpGet]
        [ActionName("Create")]
        public ActionResult Create_Get()
        {
            GroceryRepository groceryRepository = new GroceryRepository();
            var groceryList = groceryRepository.GroceryTypes.ToList();
            ViewBag.GroceryItemTypeId = new SelectList(groceryList, "GroceryItemTypeId", "GroceryItemTypeName");
            //ViewBag.GroceryItemTypeId = new SelectList(groceryRepository.GroceryTypes, "GroceryItemTypeId", "GroceryItemTypeName");
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post(Grocery grocery)
        {
            //Grocery grocery = new Grocery();

            if (ModelState.IsValid)
            {
                
                GroceryRepository groceryRepository = new GroceryRepository();
                var groceryList = groceryRepository.GroceryTypes.ToList();
               // ViewData["GroceryItemType"] = new SelectList(groceryList, "GroceryItemTypeId", "GroceryItemTypeName");

                // ViewBag.GroceryItemTypeId = new SelectList(groceryRepository.GroceryTypes, "GroceryItemTypeId", "GroceryItemTypeName");
                groceryRepository.Add(grocery);

                ViewBag.GroceryItemType = new SelectList(groceryList, "GroceryItemTypeId", "GroceryItemTypeName");


                return RedirectToAction("Index");

            }
            return View();
        }

        [HttpGet]
        [ActionName("Edit")]
        public ActionResult Get_Edit(int id)
        {
            GroceryRepository groceryRepository = new GroceryRepository();
            Grocery grocery= groceryRepository.Groceries.Single(gr => gr.GroceryItemId == id);
            var groceryList = groceryRepository.GroceryTypes.ToList();

            //ViewBag.GroceryItemTypeId = new SelectList(groceryList, "GroceryItemTypeId", "GroceryItemTypeName");


           
                List<SelectListItem> selectListItems = new List<SelectListItem>();

                foreach (GroceryType gr in groceryRepository.GroceryTypes)
                {
                    SelectListItem selectListItem = new SelectListItem
                    {
                        Text = gr.GroceryItemTypeName,
                        Value = gr.GroceryItemTypeId.ToString()

                        //Selected = department.IsSelected.HasValue ? department.IsSelected.Value : false
                    };
                    selectListItems.Add(selectListItem);
                }

                ViewBag.GroceryItemTypeId = selectListItems;
              
         

            return View(grocery);
        }

        [HttpPost]
        public ActionResult Edit(Grocery grocery)
        {
            if (ModelState.IsValid)
            {
                GroceryRepository groceryRepository = new GroceryRepository();
                groceryRepository.EditGrocery(grocery);
                return RedirectToAction("Index");
            }

            return View(grocery);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            GroceryRepository groceryRepository = new GroceryRepository();
            Grocery grocery= groceryRepository.Groceries.Single(gr => gr.GroceryItemId == id);
           
            if (ModelState.IsValid)
            {
                groceryRepository.DeleteGrocery(grocery);
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

Family/Controllers/TaskJobController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Family.Models;

namespace Family.Controllers
{
    public class TaskJobController : Controller
    {
        private TaskContext db = new TaskContext();

        // GET: TaskJob
        public ActionResult PracticeView()
        {
            return View();
        }
        public ActionResult Index()
        {
            var tasks = db.Tasks.Include(t => t.FamilyMember);
            return View(tasks.ToList());
        }

        public ActionResult TaskByFamily()
        {
            var tasks = db.Tasks.Include(t => t.FamilyMember)
                .GroupBy(x => x.FamilyMember.Name)
                .Select(y => new TaskFamilyTotal
                {
                    Name = y.Key,
                    Total = y.Count()
                }).ToList().OrderByDescending(y => y.Total);
            return View(tasks);
        }

        // GET: TaskJob/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: TaskJob/Create
        public ActionResult Create()
        {
            ViewBag.Task_FamilyMemberId = new SelectList(db.FamilyMembers, "FamilyMemberId", "Name");
            return View();
        }

        // POST: TaskJob/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Task_Id,Task_Name,Task_Preparation,Task_Duration,Task_Status,Task_FamilyMemberId")] Task task)
        {
            if (string.IsNullOrEmpty(task.Task_Name))
            {
                ModelState.AddModelError("Task_Name","Name Field is required");
            }
            if (ModelState.IsValid)
            {
                db.Tasks.Add(task);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Task_FamilyMemberId = new SelectList(db.FamilyMembers, "FamilyMemberId", "Name", task.Task_FamilyMemberId);
            return View(task);
        }

        // GET: TaskJob/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            ViewBag.Task_FamilyMemberId = new SelectList(db.FamilyMembers, "FamilyMemberId", "Name", task.Task_FamilyMemberId);
            return View(task);
        }

        // POST: TaskJob/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
       // public ActionResult Edit([Bind(Include = "Task_Id,Task_Name,Task_Preparation,Task_Duration,Task_Status,Task_FamilyMemberId")] Task task)
       public ActionResult Edit([Bind(Exclude  = "Task_Name")] Task task)
        {
            Task Taskdb = db.Tasks.Single(x => x.Task_Id == task.Task_Id);

            //Taskdb.Task_Id = task.Task_Id;
            Taskdb.Task_Preparation = task.Task_Preparation;
            Taskdb.Task_Duration = task.Task_Duration;
            Taskdb.Task_Status = task.Task_Status;
            Taskdb.Task_FamilyMemberId = task.Task_FamilyMemberId;
            task.Task_Name = Taskdb.Task_Name;


            if (ModelState.IsValid)
            {
                db.Entry(Taskdb).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Task_FamilyMemberId = new SelectList(db.FamilyMembers, "FamilyMemberId", "Name", task.Task_FamilyMemberId);
            return View(task);
        }

        // GET: TaskJob/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: TaskJob/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Task task = db.Tasks.Find(id);
            db.Tasks.Remove(task);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Family/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">
    <title>Sidebar template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="~/Content/Bar.css" rel="stylesheet" />


</head>
<body>


    <div class="page-wrapper chiller-theme toggled">
        <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
            <i class="fas fa-bars"></i>
        </a>
        <nav id="sidebar" class="sidebar-wrapper">
            <div class="sidebar-content">
                <div class="sidebar-brand">
                    <a href="#">pro sidebar</a>
                    <div id="close-sidebar">
                        <i class="fas fa-times"></i>
                    </div>
                </div>
                <div class="sidebar-header">
                    <div class="user-pic">
                        <img class="img-responsive img-rounded" src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                             alt="User picture">
                    </div>
                    <div class="user-info">
                        <span class="user-name">
                            Jhon
                            <strong>Smith</strong>
                        </span>
                        <span class="user-role">Administrator</span>
                        <span class="user-status">
                            <i class="fa fa-circle"></i>
                            <span>Online</span>
                        </span>
                    </div>
                </div>
                <!-- sidebar-header  -->
                <div class="sidebar-search">
                    <div>
                        <div class="input-group">
                            <input type="text" class="form-control search-menu" placeholder="Search...">
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- sidebar-search  -->
                <div class="sidebar-menu">
                    <ul>
                        <li class="header-menu">
                            <span>Menu</span>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="fa fa-tachometer-alt"></i>
                                <span>Family</span>
                                @*<span class="badge badge-pill badge-warning">New</span>*@
                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    <li>@Html.ActionLink("FamilyMembers", "ViewAll", "FamilyMember")</li>
                                    <li>@Html.ActionLink("FamilyMember Details", "ViewFamilyMemberWithDetails", "FamilyMember")</li>

                                    <li>@Html.ActionLink("FamilyMember Type", "Index", "FamilyMemberType")</li>
                                    @*<li>
                                        <a href="#">Dashboard 3</a>
                                    </li>*@
                                </ul>
                            </div>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="fa fa-shopping-cart"></i>
                                <span>Shop Grocery</span>
                                <span class="badge badge-pill badge-danger">3</span>
                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    <li>
                                        @Html.ActionLink("View Shopping List","Index","ShopGrocery")
                                        @*<a href="#">
                                            View Shopping List

                                        </a>*@
                                    </li>
                                    <li>
                                        @Html.ActionLink("View Item Type","ItemType","GroceryType")
                                    </li>
                                    <li>
                                        <a href="#">Credit cart</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="far fa-gem"></i>
                                <span>Duties</span>
                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    <li>
                                        @Html.ActionLink("Task", "Index", "TaskJob")
                                    </li>
                                    <li>
                                        @Html.ActionLink("TaskByFamily", "TaskByFamily", "TaskJob")
                                    </li>
                                    <li>
                                        <a href="#">Tables</a>
                                    </li>
                                    <li>
                                        <a href="#">Icons</a>
                                    </li>
                                    <li>
                                        <a href="#">Forms</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="fa fa-chart-line"></i>
                                <span>Charts</span>
                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    <li>
                                        <a href="#">Pie chart</a>
                                    </li>
                                    <li>
                                        <a href="#">Line chart</a>
                                    </li>
                                    <li>
                                        <a href="#">Bar chart</a>
                                    </li>
                                    <li>
                                        <a href="#">Histogram</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="fa fa-globe"></i>
                                <span>Maps</span>
                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    <li>
                                        <a href="#">Google maps</a>
                                    </li>
                                    <li>
                                        <a href="#">Open street map</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="header-menu">
                            <span>Extra</span>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-book"></i>
                                <span>Documentation</span>
                                <span class="badge badge-pill badge-primary">Beta</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-calendar"></i>
                                <span>Calendar</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-folder"></i>
                                <span>Examples</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- sidebar-menu  -->
            </div>
            <!-- sidebar-content  -->
            <div class="sidebar-footer">
                <a href="#">
                    <i class="fa fa-bell"></i>
                    <span class="badge badge-pill badge-warning notification">3</span>
                </a>
                <a href="#">
                    <i class="fa fa-envelope"></i>
                    <span class="badge badge-pill badge-success notification">7</span>
                </a>
                <a href="#">
                    <i class="fa fa-cog"></i>
                    <span class="badge-sonar"></span>
                </a>
                <a href="#">
                    <i class="fa fa-power-off"></i>
                </a>
            </div>
        </nav>
        <!-- sidebar-wrapper  -->
        <main class="page-content">
            <div class="container-fluid">
                @RenderBody()
                <footer class="text-center">
                    <div class="mb-2" style="font-size:small">
                        <large>
                            © 2024 made with <i class="fa fa-heart" style="color:red"></i> by - <a target="_blank" rel="noopener noreferrer" href="https://azouaoui.netlify.com">
                                Jesmi Raithore
                            </a>
                        </large>
                    </div>
                    @*<div>
                        <a href="https://github.com/azouaoui-med" target="_blank">
                            <img alt="GitHub followers" src="https://img.shields.io/github/followers/azouaoui-med?label=github&style=social" />
                        </a>
                        <a href="https://twitter.com/azouaoui_med" target="_blank">
                            <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/azouaoui_med?label=twitter&style=social" />
                        </a>
                    </div>*@
                </footer>
            </div>
        </main>
        <!-- page-content" -->
    </div>


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript">

        $(".sidebar-dropdown > a").click(function () {
            $(".sidebar-submenu").slideUp(200);
            if (
                $(this)
                    .parent()
                    .hasClass("active")
            ) {
                $(".sidebar-dropdown").removeClass("active");
                $(this)
                    .parent()
                    .removeClass("active");
            } else {
                $(".sidebar-dropdown").removeClass("active");
                $(this)
                    .next(".sidebar-submenu")
                    .slideDown(200);
                $(this)
                    .parent()
                    .addClass("active");
            }
        });

        $("#close-sidebar").click(function () {
            $(".page-wrapper").removeClass("toggled");
        });
        $("#show-sidebar").click(function () {
            $(".page-wrapper").addClass("toggled");
        });

    </script>
</body>
</html>